#!/usr/bin/env python3
"""Regenerate the clean-URL copies: <page>/index.html for every root <page>.html except index.html.

GitHub Pages serves /privacy/ from privacy/index.html, so each copy is the root page with its
relative paths pointed one level up. Edit the root page, then run:  python3 tools/mirror.py
"""
import pathlib, re

site = pathlib.Path(__file__).resolve().parent.parent
pages = sorted(p for p in site.glob('*.html') if p.name != 'index.html')
names = [p.stem for p in pages]

for page in pages:
    html = page.read_text()
    html = html.replace('href="assets/', 'href="../assets/')
    html = html.replace('href="./"', 'href="../"')
    html = re.sub(r'href="(' + '|'.join(map(re.escape, names)) + r')\.html', r'href="../\1.html', html)
    note = f'<!-- Same page as ../{page.name} so the clean URL /{page.stem}/ works. Generated by tools/mirror.py; edit {page.name} and re-run it. -->\n'
    html = html.replace('<html lang="en">\n', '<html lang="en">\n' + note, 1)
    out = site / page.stem / 'index.html'
    out.parent.mkdir(exist_ok=True)
    out.write_text(html)
    print(f'{page.name} -> {page.stem}/index.html')
